In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv("50_Startups.csv")

In [3]:
dataset

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87              NaN  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08             NaN        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
R&D Spend          50 non-null float64
Administration     49 non-null float64
Marketing Spend    49 non-null float64
State              50 non-null object
Profit             50 non-null float64
dtypes: float64(4), object(1)
memory usage: 2.0+ KB


In [5]:
dataset.isnull().any()

R&D Spend          False
Administration      True
Marketing Spend     True
State              False
Profit             False
dtype: bool

In [6]:
dataset["Administration"].fillna(dataset["Administration"].mean(),inplace = True)
dataset["Marketing Spend"].fillna(dataset["Marketing Spend"].mean(),inplace = True)

In [7]:
dataset.isnull().any()

R&D Spend          False
Administration     False
Marketing Spend    False
State              False
Profit             False
dtype: bool

In [8]:
x=dataset.iloc[:,:5].values
y=dataset.iloc[:,4:].values

In [9]:
x

array([[165349.2, 136897.8, 471784.1, 'New York', 192261.83],
       [162597.7, 151377.59, 443898.53, 'California', 191792.06],
       [153441.51, 101145.55, 407934.54, 'Florida', 191050.39],
       [144372.41, 118671.85, 383199.62, 'New York', 182901.99],
       [142107.34, 91391.77, 366168.42, 'Florida', 166187.94],
       [131876.9, 99814.71, 362861.36, 'New York', 156991.12],
       [134615.46, 147198.87, 212725.26673469393, 'California',
        156122.51],
       [130298.13, 145530.06, 323876.68, 'Florida', 155752.6],
       [120542.52, 148718.95, 311613.29, 'New York', 152211.77],
       [123334.88, 108679.17, 304981.62, 'California', 149759.96],
       [101913.08, 121564.03816326526, 229160.95, 'Florida', 146121.95],
       [100671.96, 91790.61, 249744.55, 'California', 144259.4],
       [93863.75, 127320.38, 249839.44, 'Florida', 141585.52],
       [91992.39, 135495.07, 252664.93, 'California', 134307.35],
       [119943.24, 156547.42, 256512.92, 'Florida', 132602.65],
       

In [10]:
y

array([[192261.83],
       [191792.06],
       [191050.39],
       [182901.99],
       [166187.94],
       [156991.12],
       [156122.51],
       [155752.6 ],
       [152211.77],
       [149759.96],
       [146121.95],
       [144259.4 ],
       [141585.52],
       [134307.35],
       [132602.65],
       [129917.04],
       [126992.93],
       [125370.37],
       [124266.9 ],
       [122776.86],
       [118474.03],
       [111313.02],
       [110352.25],
       [108733.99],
       [108552.04],
       [107404.34],
       [105733.54],
       [105008.31],
       [103282.38],
       [101004.64],
       [ 99937.59],
       [ 97483.56],
       [ 97427.84],
       [ 96778.92],
       [ 96712.8 ],
       [ 96479.51],
       [ 90708.19],
       [ 89949.14],
       [ 81229.06],
       [ 81005.76],
       [ 78239.91],
       [ 77798.83],
       [ 71498.49],
       [ 69758.98],
       [ 65200.33],
       [ 64926.08],
       [ 49490.75],
       [ 42559.73],
       [ 35673.41],
       [ 14681.4 ]])

In [11]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer([('one',OneHotEncoder(),[3])],remainder='passthrough')
x=ct.fit_transform(x)

In [12]:
dataset["State"].unique()
#['California','Florida','New York']

array(['New York', 'California', 'Florida'], dtype=object)

In [13]:
x

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1, 192261.83],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53, 191792.06],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54, 191050.39],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62, 182901.99],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42, 166187.94],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36, 156991.12],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 212725.26673469393,
        156122.51],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68, 155752.6],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29, 152211.77],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62, 149759.96],
       [0.0, 1.0, 0.0, 101913.08, 121564.03816326526, 229160.95,
        146121.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55, 144259.4],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44, 141585.52],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93, 134307.35],
       [0.0, 1.0, 0.0, 119

In [90]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [91]:
x_train.shape

(40, 7)

In [92]:
y_train.shape

(40, 1)

In [157]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [158]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [173]:
reg=Sequential()

In [174]:
reg.add(Dense(units=7,kernel_initializer= "random_uniform",activation= "relu"))

In [175]:
reg.add(Dense(units=14,kernel_initializer= "random_uniform",activation= "relu"))

In [176]:
reg.add(Dense(units=14,kernel_initializer= "random_uniform",activation= "relu"))

In [177]:
reg.add(Dense(units=14,kernel_initializer= "random_uniform",activation= "relu"))

In [178]:
reg.add(Dense(units=14,kernel_initializer= "random_uniform",activation= "relu"))

In [179]:
reg.add(Dense(units=14,kernel_initializer= "random_uniform",activation= "relu"))

In [180]:
reg.add(Dense(units=1,kernel_initializer= "random_uniform",activation= "relu"))

In [181]:
reg.compile(optimizer="rmsprop",loss="mean_squared_error",metrics=["accuracy"])

In [182]:
reg.fit(x_train,y_train,epochs=500)

Epoch 1/500
40/40 [==============================] - 0s 8ms/sample - loss: 13615995084.8000 - acc: 0.0000e+00
Epoch 2/500
40/40 [==============================] - 0s 68us/sample - loss: 13615994880.0000 - acc: 0.0000e+00
Epoch 3/500
40/40 [==============================] - 0s 152us/sample - loss: 13615992012.8000 - acc: 0.0000e+00
Epoch 4/500
40/40 [==============================] - 0s 142us/sample - loss: 13615991808.0000 - acc: 0.0000e+00
Epoch 5/500
40/40 [==============================] - 0s 175us/sample - loss: 13615990374.4000 - acc: 0.0000e+00
Epoch 6/500
40/40 [==============================] - 0s 125us/sample - loss: 13615989760.0000 - acc: 0.0000e+00
Epoch 7/500
40/40 [==============================] - 0s 149us/sample - loss: 13615989555.2000 - acc: 0.0000e+00
Epoch 8/500
40/40 [==============================] - 0s 100us/sample - loss: 13615987916.8000 - acc: 0.0000e+00
Epoch 9/500
40/40 [==============================] - 0s 125us/sample - loss: 13615985868.8000 - acc: 0.0000

40/40 [==============================] - 0s 128us/sample - loss: 13611504025.6000 - acc: 0.0000e+00
Epoch 74/500
40/40 [==============================] - 0s 199us/sample - loss: 13611154636.8000 - acc: 0.0000e+00
Epoch 75/500
40/40 [==============================] - 0s 123us/sample - loss: 13610819993.6000 - acc: 0.0000e+00
Epoch 76/500
40/40 [==============================] - 0s 125us/sample - loss: 13610434560.0000 - acc: 0.0000e+00
Epoch 77/500
40/40 [==============================] - 0s 100us/sample - loss: 13610014310.4000 - acc: 0.0000e+00
Epoch 78/500
40/40 [==============================] - 0s 125us/sample - loss: 13609589760.0000 - acc: 0.0000e+00
Epoch 79/500
40/40 [==============================] - 0s 105us/sample - loss: 13609150873.6000 - acc: 0.0000e+00
Epoch 80/500
40/40 [==============================] - 0s 149us/sample - loss: 13608704000.0000 - acc: 0.0000e+00
Epoch 81/500
40/40 [==============================] - 0s 100us/sample - loss: 13608185241.6000 - acc: 0.0000e

40/40 [==============================] - 0s 151us/sample - loss: 13421160652.8000 - acc: 0.0000e+00
Epoch 146/500
40/40 [==============================] - 0s 125us/sample - loss: 13413235916.8000 - acc: 0.0000e+00
Epoch 147/500
40/40 [==============================] - 0s 124us/sample - loss: 13404436070.4000 - acc: 0.0000e+00
Epoch 148/500
40/40 [==============================] - 0s 150us/sample - loss: 13395945881.6000 - acc: 0.0000e+00
Epoch 149/500
40/40 [==============================] - 0s 100us/sample - loss: 13387166105.6000 - acc: 0.0000e+00
Epoch 150/500
40/40 [==============================] - 0s 124us/sample - loss: 13378794700.8000 - acc: 0.0000e+00
Epoch 151/500
40/40 [==============================] - 0s 99us/sample - loss: 13370174259.2000 - acc: 0.0000e+00
Epoch 152/500
40/40 [==============================] - 0s 124us/sample - loss: 13361293721.6000 - acc: 0.0000e+00
Epoch 153/500
40/40 [==============================] - 0s 100us/sample - loss: 13351378534.4000 - acc: 

40/40 [==============================] - 0s 150us/sample - loss: 11683711385.6000 - acc: 0.0000e+00
Epoch 218/500
40/40 [==============================] - 0s 125us/sample - loss: 11634141593.6000 - acc: 0.0000e+00
Epoch 219/500
40/40 [==============================] - 0s 124us/sample - loss: 11579205222.4000 - acc: 0.0000e+00
Epoch 220/500
40/40 [==============================] - 0s 125us/sample - loss: 11521903001.6000 - acc: 0.0000e+00
Epoch 221/500
40/40 [==============================] - 0s 151us/sample - loss: 11475338649.6000 - acc: 0.0000e+00
Epoch 222/500
40/40 [==============================] - 0s 174us/sample - loss: 11423913574.4000 - acc: 0.0000e+00
Epoch 223/500
40/40 [==============================] - 0s 150us/sample - loss: 11372633702.4000 - acc: 0.0000e+00
Epoch 224/500
40/40 [==============================] - 0s 125us/sample - loss: 11319437312.0000 - acc: 0.0000e+00
Epoch 225/500
40/40 [==============================] - 0s 123us/sample - loss: 11263629414.4000 - acc:

40/40 [==============================] - 0s 125us/sample - loss: 5479571353.6000 - acc: 0.0000e+00
Epoch 290/500
40/40 [==============================] - 0s 149us/sample - loss: 5378400102.4000 - acc: 0.0000e+00
Epoch 291/500
40/40 [==============================] - 0s 150us/sample - loss: 5279411097.6000 - acc: 0.0000e+00
Epoch 292/500
40/40 [==============================] - 0s 100us/sample - loss: 5160714649.6000 - acc: 0.0000e+00
Epoch 293/500
40/40 [==============================] - 0s 100us/sample - loss: 5035906048.0000 - acc: 0.0000e+00
Epoch 294/500
40/40 [==============================] - 0s 125us/sample - loss: 4904782028.8000 - acc: 0.0000e+00
Epoch 295/500
40/40 [==============================] - 0s 75us/sample - loss: 4792076083.2000 - acc: 0.0000e+00
Epoch 296/500
40/40 [==============================] - 0s 100us/sample - loss: 4682180812.8000 - acc: 0.0000e+00
Epoch 297/500
40/40 [==============================] - 0s 101us/sample - loss: 4569688576.0000 - acc: 0.0000e+0

40/40 [==============================] - 0s 125us/sample - loss: 1133121305.6000 - acc: 0.0000e+00
Epoch 362/500
40/40 [==============================] - 0s 99us/sample - loss: 1126955200.0000 - acc: 0.0000e+00
Epoch 363/500
40/40 [==============================] - 0s 100us/sample - loss: 1118677350.4000 - acc: 0.0000e+00
Epoch 364/500
40/40 [==============================] - 0s 125us/sample - loss: 1110280627.2000 - acc: 0.0000e+00
Epoch 365/500
40/40 [==============================] - 0s 125us/sample - loss: 1103702476.8000 - acc: 0.0000e+00
Epoch 366/500
40/40 [==============================] - 0s 125us/sample - loss: 1093110016.0000 - acc: 0.0000e+00
Epoch 367/500
40/40 [==============================] - 0s 125us/sample - loss: 1086626726.4000 - acc: 0.0000e+00
Epoch 368/500
40/40 [==============================] - 0s 141us/sample - loss: 1077717606.4000 - acc: 0.0000e+00
Epoch 369/500
40/40 [==============================] - 0s 124us/sample - loss: 1069172684.8000 - acc: 0.0000e+0

40/40 [==============================] - 0s 125us/sample - loss: 675028748.8000 - acc: 0.0000e+00
Epoch 435/500
40/40 [==============================] - 0s 125us/sample - loss: 669807488.0000 - acc: 0.0000e+00
Epoch 436/500
40/40 [==============================] - 0s 99us/sample - loss: 666024844.8000 - acc: 0.0000e+00
Epoch 437/500
40/40 [==============================] - 0s 100us/sample - loss: 662275321.6000 - acc: 0.0000e+00
Epoch 438/500
40/40 [==============================] - 0s 125us/sample - loss: 659998169.6000 - acc: 0.0000e+00
Epoch 439/500
40/40 [==============================] - 0s 125us/sample - loss: 658385388.8000 - acc: 0.0000e+00
Epoch 440/500
40/40 [==============================] - 0s 149us/sample - loss: 656501184.0000 - acc: 0.0000e+00
Epoch 441/500
40/40 [==============================] - 0s 174us/sample - loss: 652079360.0000 - acc: 0.0000e+00
Epoch 442/500
40/40 [==============================] - 0s 125us/sample - loss: 648175219.2000 - acc: 0.0000e+00
Epoch 4

In [183]:
pred=reg.predict(x_test)

In [184]:
print(pred)

[[ 80246.   ]
 [126977.945]
 [104700.164]
 [ 54788.07 ]
 [180561.19 ]
 [104788.89 ]
 [ 79327.56 ]
 [ 90273.45 ]
 [ 80822.19 ]
 [145253.97 ]]


In [185]:
y_test

array([[103282.38],
       [144259.4 ],
       [146121.95],
       [ 77798.83],
       [191050.39],
       [105008.31],
       [ 81229.06],
       [ 97483.56],
       [110352.25],
       [166187.94]])