In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv("bank.csv")

In [3]:
dataset

age            job   marital  education default  balance housing loan  \
0       59         admin.   married  secondary      no     2343     yes   no   
1       56         admin.   married  secondary      no       45      no   no   
2       41     technician   married  secondary      no     1270     yes   no   
3       55       services   married  secondary      no     2476     yes   no   
4       54         admin.   married   tertiary      no      184      no   no   
5       42     management    single   tertiary      no        0     yes  yes   
6       56     management   married   tertiary      no      830     yes  yes   
7       60        retired  divorced  secondary      no      545     yes   no   
8       37     technician   married  secondary      no        1     yes   no   
9       28       services    single  secondary      no     5090     yes   no   
10      38         admin.    single  secondary      no      100     yes   no   
11      30    blue-collar   married  secondary      no      309     yes   no   
12      29     management   married   tertiary      no      199     yes  yes   
13      46    blue-collar    single   tertiary      no      460     yes   no   
14      31     technician    single   tertiary      no      703     yes   no   
15      35     management  divorced   tertiary      no     3837     yes   no   
16      32    blue-collar    single    primary      no      611     yes   no   
17      49       services   married  secondary      no       -8     yes   no   
18      41         admin.   married  secondary      no       55     yes   no   
19      49         admin.  divorced  secondary      no      168     yes  yes   
20      28         admin.  divorced  secondary      no      785     yes   no   
21      43     management    single   tertiary      no     2067     yes   no   
22      43     management  divorced   tertiary      no      388     yes   no   
23      43    blue-collar   married    primary      no     -192     yes   no   
24      37     unemployed    single  secondary      no      381     yes   no   
25      35    blue-collar    single  secondary      no       40     yes   no   
26      31     technician    single   tertiary      no       22     yes   no   
27      43    blue-collar    single  secondary      no        3     yes   no   
28      31         admin.   married  secondary      no      307     yes   no   
29      28    blue-collar    single  secondary      no      759     yes   no   
...    ...            ...       ...        ...     ...      ...     ...  ...   
11132   32    blue-collar   married  secondary      no     -325     yes  yes   
11133   37     management   married   tertiary      no     1594     yes   no   
11134   58  self-employed   married   tertiary      no     2596      no   no   
11135   36       services  divorced  secondary      no      115      no   no   
11136   31     management    single   tertiary      no        0     yes   no   
11137   49        retired   married    unknown      no      247      no   no   
11138   32     technician   married  secondary      no      235     yes   no   
11139   30  self-employed    single   tertiary      no     2593      no   no   
11140   55       services  divorced  secondary      no     2166     yes   no   
11141   32    blue-collar   married  secondary      no      130     yes   no   
11142   52         admin.  divorced  secondary      no       48      no  yes   
11143   38     unemployed  divorced  secondary      no      189     yes  yes   
11144   60        retired   married  secondary      no        0     yes   no   
11145   60        retired  divorced   tertiary      no     -134      no   no   
11146   30         admin.   married  secondary     yes       23      no  yes   
11147   44     unemployed   married  secondary      no        0      no   no   
11148   32    blue-collar   married  secondary      no        1     yes   no   
11149   46   entrepreneur   married  secondary      no     3317      no   no   
11150  

In [4]:
dataset.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [5]:
x=dataset.iloc[:,:16].values
y=dataset.iloc[:,16:].values

In [6]:
x

array([[59, 'admin.', 'married', ..., -1, 0, 'unknown'],
       [56, 'admin.', 'married', ..., -1, 0, 'unknown'],
       [41, 'technician', 'married', ..., -1, 0, 'unknown'],
       ...,
       [32, 'technician', 'single', ..., -1, 0, 'unknown'],
       [43, 'technician', 'married', ..., 172, 5, 'failure'],
       [34, 'technician', 'married', ..., -1, 0, 'unknown']], dtype=object)

In [7]:
y

array([['yes'],
       ['yes'],
       ['yes'],
       ...,
       ['no'],
       ['no'],
       ['no']], dtype=object)

In [8]:
dataset

age            job   marital  education default  balance housing loan  \
0       59         admin.   married  secondary      no     2343     yes   no   
1       56         admin.   married  secondary      no       45      no   no   
2       41     technician   married  secondary      no     1270     yes   no   
3       55       services   married  secondary      no     2476     yes   no   
4       54         admin.   married   tertiary      no      184      no   no   
5       42     management    single   tertiary      no        0     yes  yes   
6       56     management   married   tertiary      no      830     yes  yes   
7       60        retired  divorced  secondary      no      545     yes   no   
8       37     technician   married  secondary      no        1     yes   no   
9       28       services    single  secondary      no     5090     yes   no   
10      38         admin.    single  secondary      no      100     yes   no   
11      30    blue-collar   married  secondary      no      309     yes   no   
12      29     management   married   tertiary      no      199     yes  yes   
13      46    blue-collar    single   tertiary      no      460     yes   no   
14      31     technician    single   tertiary      no      703     yes   no   
15      35     management  divorced   tertiary      no     3837     yes   no   
16      32    blue-collar    single    primary      no      611     yes   no   
17      49       services   married  secondary      no       -8     yes   no   
18      41         admin.   married  secondary      no       55     yes   no   
19      49         admin.  divorced  secondary      no      168     yes  yes   
20      28         admin.  divorced  secondary      no      785     yes   no   
21      43     management    single   tertiary      no     2067     yes   no   
22      43     management  divorced   tertiary      no      388     yes   no   
23      43    blue-collar   married    primary      no     -192     yes   no   
24      37     unemployed    single  secondary      no      381     yes   no   
25      35    blue-collar    single  secondary      no       40     yes   no   
26      31     technician    single   tertiary      no       22     yes   no   
27      43    blue-collar    single  secondary      no        3     yes   no   
28      31         admin.   married  secondary      no      307     yes   no   
29      28    blue-collar    single  secondary      no      759     yes   no   
...    ...            ...       ...        ...     ...      ...     ...  ...   
11132   32    blue-collar   married  secondary      no     -325     yes  yes   
11133   37     management   married   tertiary      no     1594     yes   no   
11134   58  self-employed   married   tertiary      no     2596      no   no   
11135   36       services  divorced  secondary      no      115      no   no   
11136   31     management    single   tertiary      no        0     yes   no   
11137   49        retired   married    unknown      no      247      no   no   
11138   32     technician   married  secondary      no      235     yes   no   
11139   30  self-employed    single   tertiary      no     2593      no   no   
11140   55       services  divorced  secondary      no     2166     yes   no   
11141   32    blue-collar   married  secondary      no      130     yes   no   
11142   52         admin.  divorced  secondary      no       48      no  yes   
11143   38     unemployed  divorced  secondary      no      189     yes  yes   
11144   60        retired   married  secondary      no        0     yes   no   
11145   60        retired  divorced   tertiary      no     -134      no   no   
11146   30         admin.   married  secondary     yes       23      no  yes   
11147   44     unemployed   married  secondary      no        0      no   no   
11148   32    blue-collar   married  secondary      no        1     yes   no   
11149   46   entrepreneur   married  secondary      no     3317      no   no   
11150  

In [9]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct1=ColumnTransformer([('one',OneHotEncoder(),[1,2,3,4,6,7,8,10,15])],remainder="passthrough")
ct2=ColumnTransformer([('one',OneHotEncoder(),[0])],remainder="passthrough")
x=ct1.fit_transform(x)
y=ct2.fit_transform(y)

In [10]:
x

array([[1.0, 0.0, 0.0, ..., 1, -1, 0],
       [1.0, 0.0, 0.0, ..., 1, -1, 0],
       [0.0, 0.0, 0.0, ..., 1, -1, 0],
       ...,
       [0.0, 0.0, 0.0, ..., 2, -1, 0],
       [0.0, 0.0, 0.0, ..., 2, 172, 5],
       [0.0, 0.0, 0.0, ..., 1, -1, 0]], dtype=object)

In [11]:
y

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [55]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [56]:
x_train.shape

(8929, 51)

In [57]:
y_train.shape

(8929, 2)

In [58]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [59]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [60]:
cat=Sequential()

In [61]:
cat.add(Dense(units=51,kernel_initializer= "random_uniform",activation= "relu"))

In [62]:
cat.add(Dense(units=102,kernel_initializer= "random_uniform",activation= "relu"))

In [63]:
cat.add(Dense(units=102,kernel_initializer= "random_uniform",activation= "relu"))

In [64]:
cat.add(Dense(units=102,kernel_initializer= "random_uniform",activation= "relu"))

In [65]:
cat.add(Dense(units=102,kernel_initializer= "random_uniform",activation= "relu"))

In [66]:
cat.add(Dense(units=2,kernel_initializer= "random_uniform",activation= "softmax"))

In [67]:
cat.compile(optimizer="rmsprop",loss="categorical_crossentropy",metrics=["accuracy"])

In [68]:
cat.fit(x_train,y_train,epochs=450)

Epoch 1/450
8929/8929 [==============================] - 1s 92us/sample - loss: 0.4375 - acc: 0.7993
Epoch 2/450
8929/8929 [==============================] - 1s 67us/sample - loss: 0.3685 - acc: 0.8454
Epoch 3/450
8929/8929 [==============================] - 1s 68us/sample - loss: 0.3549 - acc: 0.8549
Epoch 4/450
8929/8929 [==============================] - 1s 70us/sample - loss: 0.3431 - acc: 0.8588
Epoch 5/450
8929/8929 [==============================] - 1s 74us/sample - loss: 0.3362 - acc: 0.8627
Epoch 6/450
8929/8929 [==============================] - 1s 70us/sample - loss: 0.3256 - acc: 0.8698
Epoch 7/450
8929/8929 [==============================] - 1s 69us/sample - loss: 0.3231 - acc: 0.8694
Epoch 8/450
8929/8929 [==============================] - 1s 71us/sample - loss: 0.3158 - acc: 0.8720
Epoch 9/450
8929/8929 [==============================] - 1s 70us/sample - loss: 0.3106 - acc: 0.8750
Epoch 10/450
8929/8929 [==============================] - 1s 69us/sample - loss: 0.3074 - a

8929/8929 [==============================] - 1s 67us/sample - loss: 0.0941 - acc: 0.9660
Epoch 82/450
8929/8929 [==============================] - 1s 66us/sample - loss: 0.0898 - acc: 0.9665
Epoch 83/450
8929/8929 [==============================] - 1s 66us/sample - loss: 0.0931 - acc: 0.9692
Epoch 84/450
8929/8929 [==============================] - 1s 69us/sample - loss: 0.0895 - acc: 0.9664
Epoch 85/450
8929/8929 [==============================] - 1s 67us/sample - loss: 0.0893 - acc: 0.9680
Epoch 86/450
8929/8929 [==============================] - 1s 82us/sample - loss: 0.0883 - acc: 0.9708
Epoch 87/450
8929/8929 [==============================] - 1s 75us/sample - loss: 0.0812 - acc: 0.9699
Epoch 88/450
8929/8929 [==============================] - 1s 67us/sample - loss: 0.0845 - acc: 0.9701
Epoch 89/450
8929/8929 [==============================] - 1s 68us/sample - loss: 0.0847 - acc: 0.9711
Epoch 90/450
8929/8929 [==============================] - 1s 69us/sample - loss: 0.0765 - acc: 

8929/8929 [==============================] - 1s 74us/sample - loss: 0.0602 - acc: 0.9866
Epoch 161/450
8929/8929 [==============================] - 1s 68us/sample - loss: 0.0697 - acc: 0.9848
Epoch 162/450
8929/8929 [==============================] - 1s 70us/sample - loss: 0.0579 - acc: 0.9864
Epoch 163/450
8929/8929 [==============================] - 1s 70us/sample - loss: 0.0528 - acc: 0.9857
Epoch 164/450
8929/8929 [==============================] - 1s 66us/sample - loss: 0.0534 - acc: 0.9841
Epoch 165/450
8929/8929 [==============================] - 1s 65us/sample - loss: 0.0463 - acc: 0.9873
Epoch 166/450
8929/8929 [==============================] - 1s 66us/sample - loss: 0.0651 - acc: 0.9866
Epoch 167/450
8929/8929 [==============================] - 1s 66us/sample - loss: 0.0448 - acc: 0.9870
Epoch 168/450
8929/8929 [==============================] - 1s 64us/sample - loss: 0.0487 - acc: 0.9859
Epoch 169/450
8929/8929 [==============================] - 1s 72us/sample - loss: 0.049

8929/8929 [==============================] - 1s 68us/sample - loss: 0.0461 - acc: 0.9885
Epoch 240/450
8929/8929 [==============================] - 1s 74us/sample - loss: 0.0456 - acc: 0.9900
Epoch 241/450
8929/8929 [==============================] - 1s 76us/sample - loss: 0.0422 - acc: 0.9890
Epoch 242/450
8929/8929 [==============================] - 1s 69us/sample - loss: 0.0550 - acc: 0.9884
Epoch 243/450
8929/8929 [==============================] - 1s 66us/sample - loss: 0.0559 - acc: 0.9900
Epoch 244/450
8929/8929 [==============================] - 1s 66us/sample - loss: 0.0477 - acc: 0.9910
Epoch 245/450
8929/8929 [==============================] - 1s 68us/sample - loss: 0.0375 - acc: 0.9915
Epoch 246/450
8929/8929 [==============================] - 1s 89us/sample - loss: 0.0529 - acc: 0.9931
Epoch 247/450
8929/8929 [==============================] - 1s 77us/sample - loss: 0.0426 - acc: 0.9905
Epoch 248/450
8929/8929 [==============================] - 1s 70us/sample - loss: 0.044

8929/8929 [==============================] - 1s 65us/sample - loss: 0.0429 - acc: 0.9909
Epoch 319/450
8929/8929 [==============================] - 1s 65us/sample - loss: 0.0311 - acc: 0.9917
Epoch 320/450
8929/8929 [==============================] - 1s 66us/sample - loss: 0.0614 - acc: 0.9904
Epoch 321/450
8929/8929 [==============================] - 1s 68us/sample - loss: 0.0460 - acc: 0.9909
Epoch 322/450
8929/8929 [==============================] - 1s 66us/sample - loss: 0.0421 - acc: 0.9909
Epoch 323/450
8929/8929 [==============================] - 1s 65us/sample - loss: 0.0366 - acc: 0.9896
Epoch 324/450
8929/8929 [==============================] - 1s 64us/sample - loss: 0.0583 - acc: 0.9898
Epoch 325/450
8929/8929 [==============================] - 1s 70us/sample - loss: 0.0476 - acc: 0.9887
Epoch 326/450
8929/8929 [==============================] - 1s 64us/sample - loss: 0.0436 - acc: 0.9905
Epoch 327/450
8929/8929 [==============================] - 1s 63us/sample - loss: 0.059

8929/8929 [==============================] - 1s 63us/sample - loss: 0.0286 - acc: 0.9937
Epoch 398/450
8929/8929 [==============================] - 1s 71us/sample - loss: 0.0492 - acc: 0.9904
Epoch 399/450
8929/8929 [==============================] - 1s 68us/sample - loss: 0.0292 - acc: 0.9932
Epoch 400/450
8929/8929 [==============================] - 1s 70us/sample - loss: 0.0622 - acc: 0.9916
Epoch 401/450
8929/8929 [==============================] - 1s 64us/sample - loss: 0.0340 - acc: 0.9929
Epoch 402/450
8929/8929 [==============================] - 1s 69us/sample - loss: 0.0299 - acc: 0.9934
Epoch 403/450
8929/8929 [==============================] - 1s 65us/sample - loss: 0.0198 - acc: 0.9953
Epoch 404/450
8929/8929 [==============================] - 1s 67us/sample - loss: 0.0286 - acc: 0.9941
Epoch 405/450
8929/8929 [==============================] - 1s 68us/sample - loss: 0.0349 - acc: 0.9940
Epoch 406/450
8929/8929 [==============================] - 1s 69us/sample - loss: 0.040

In [69]:
pred=cat.predict(x_test)

In [70]:
pred=pred>0.5

In [71]:
pred[:4]

array([[ True, False],
       [False,  True],
       [ True, False],
       [False,  True]])

In [72]:
y_test[:4]

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.]])

In [73]:
x[0]

array([1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0,
       0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 1.0, 59, 2343, 5, 1042, 1, -1, 0], dtype=object)

In [78]:
a=cat.predict(sc.transform([[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0,
       0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 1.0, 59, 2343, 5, 1042, 1, -1, 0]]))

In [80]:
dep=["yes","no"]
prediction=dep[np.argmax(a)]

In [81]:
prediction

'no'

In [82]:
y[0]

array([0., 1.])