In [1]:
import pandas as pd
import nltk
import re

In [2]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\OWNER\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [3]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [4]:
ps=PorterStemmer()

In [5]:
data=[]

In [6]:
df=pd.read_csv('IMDB Dataset.csv')

In [7]:
df=df.iloc[:1000,:]

In [8]:
df

review sentiment
0    One of the other reviewers has mentioned that ...  positive
1    A wonderful little production. <br /><br />The...  positive
2    I thought this was a wonderful way to spend ti...  positive
3    Basically there's a family where a little boy ...  negative
4    Petter Mattei's "Love in the Time of Money" is...  positive
5    Probably my all-time favorite movie, a story o...  positive
6    I sure would like to see a resurrection of a u...  positive
7    This show was an amazing, fresh & innovative i...  negative
8    Encouraged by the positive comments about this...  negative
9    If you like original gut wrenching laughter yo...  positive
10   Phil the Alien is one of those quirky films wh...  negative
11   I saw this movie when I was about 12 when it c...  negative
12   So im not a big fan of Boll's work but then ag...  negative
13   The cast played Shakespeare.<br /><br />Shakes...  negative
14   This a fantastic movie of three prisoners who ...  positive
15   Kind of drawn in by the erotic scenes, only to...  negative
16   Some films just simply should not be remade. T...  positive
17   This movie made it into one of my top 10 most ...  negative
18   I remember this film,it was the first film i h...  positive
19   An awful film! It must have been up against so...  negative
20   After the success of Die Hard and it's sequels...  positive
21   I had the terrible misfortune of having to vie...  negative
22   What an absolutely stunning movie, if you have...  positive
23   First of all, let's get a few things straight ...  negative
24   This was the worst movie I saw at WorldFest an...  negative
25   The Karen Carpenter Story shows a little more ...  positive
26   "The Cell" is an exotic masterpiece, a dizzyin...  positive
27   This film tried to be too many things all at o...  negative
28   This movie was so frustrating. Everything seem...  negative
29   'War movie' is a Hollywood genre that has been...  positive
..                                                 ...       ...
970  *Criticism does mention spoilers*<br /><br />I...  negative
971  Possible Spoilers, Perhaps. I must say that "C...  negative
972  Hopefully the score has changed by now due to ...  positive
973  Formula movie about the illegitimate son of a ...  negative
974  Whatever rating I give BOOM is only because of...  negative
975  VIVA LA BAM This "Jackass" spin off focuses on...  negative
976  I had never heard of Larry Fessenden before bu...  negative
977  Schlocky '70s horror films...ya gotta love 'em...  negative
978  I suppose for 1961 this film was supposed to b...  negative
979  This is one of the finest films to come out of...  positive
980  Now I don't hate cheap movies. I just don't se...  negative
981  A fabulous book about a fox and his family who...  negative
982  As soon as it hits a screen, it destroys all i...  negative
983  For a film made in Senegal, based, I guess loo...  negative
984  This is a very noir kind of episode. It begins...  positive
985  The Royal Rumble has traditionally been one of...  positive
986  I remember this in a similar vein to the Young...  positive
987  Destined to be a classic before it was even co...  positive
988  Stephane Audran is the eponymous heroine of th...  positive
989  This movie was way over-hyped. A lot of the vi...  negative
990  It is incredible that there were two films wit...  negative
991  I dunno sometimes...you try and try and try to...  negative
992  Big Fat Liar is what you get when you combine ...  positive
993  Tim Robbins and John Cusack are two actors I h...  negative
994  On watching this film, I was amazed at how med...  positive
995  Nothing is sacred. Just ask Ernie Fosselius. T...  positive
996  I hated it. I hate self-aware pretentious inan...  negative
997  I usually try to be professional and construct...  negative
998  If you like me is going to see this in a film ...  negative
999  This is like a zoology textbook, given that it...  negative

[1000 rows x 2 co

In [9]:
df['sentiment'].unique()

array(['positive', 'negative'], dtype=object)

In [10]:
for i in range(0,1000):
    #print('at',i)
    #print(' ')
    review=df['review'][i]
    review=re.sub('[^a-zA-Z]',' ',review)
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review=' '.join(review)
    data.append(review)

In [11]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2000)

In [12]:
x=cv.fit_transform(data).toarray()
y=df.iloc[:,1:2].values

In [13]:
x.shape

(1000, 2000)

In [34]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 3],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [14]:
y.shape

(1000, 1)

In [15]:
for i in range (0,1000):
    if y[i]=="positive":
        y[i]=1
    elif y[i]=="negative":
        y[i]=0

In [18]:
y

array([[1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
    

In [19]:
type(x)

numpy.ndarray

In [20]:
type(y)

numpy.ndarray

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [53]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)
y_train=sc.fit_transform(y_train)
y_test=sc.fit_transform(y_test)

In [54]:
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
model=Sequential()

In [55]:
model.add(Dense(units=1000,kernel_initializer="random_uniform",activation= "relu"))
model.add(Dense(units=2000,kernel_initializer="random_uniform",activation= "relu"))
model.add(Dense(units=2000,kernel_initializer="random_uniform",activation= "relu"))
model.add(Dense(units=1,kernel_initializer="random_uniform",activation= "sigmoid"))

In [56]:
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [57]:
model.fit(x_train,y_train,epochs=100)

Epoch 1/100
800/800 [==============================] - 1s 1ms/sample - loss: -42.0589 - acc: 0.0000e+00
Epoch 2/100
800/800 [==============================] - 1s 1ms/sample - loss: -10988.5017 - acc: 0.0000e+00
Epoch 3/100
800/800 [==============================] - 1s 1ms/sample - loss: -246457.1003 - acc: 0.0000e+00
Epoch 4/100
800/800 [==============================] - 1s 1ms/sample - loss: -1898239.5900 - acc: 0.0000e+00
Epoch 5/100
800/800 [==============================] - 1s 1ms/sample - loss: -8616874.1500 - acc: 0.0000e+00
Epoch 6/100
800/800 [==============================] - 1s 1ms/sample - loss: -27488145.2000 - acc: 0.0000e+00
Epoch 7/100
800/800 [==============================] - 1s 1ms/sample - loss: -69880078.8800 - acc: 0.0000e+00
Epoch 8/100
800/800 [==============================] - 1s 1ms/sample - loss: -150216529.2800 - acc: 0.0000e+00
Epoch 9/100
800/800 [==============================] - 1s 1ms/sample - loss: -290448757.7600 - acc: 0.0000e+00
Epoch 10/100
800/800 

In [74]:
text="Excellent"
text=re.sub('[^a-zA-Z]',' ',text)
text=text.lower()
text=text.split()
text=[ps.stem(word) for word in text if not word in set(stopwords.words('english'))]
text=' '.join(text)

In [75]:
p1=model.predict(cv.transform([text]))
p1=p1>0.5 
p1

array([[ True]])

In [77]:
model.save("imdb.h5")